### Test getAuditLogData endpoint
GET {{host}}/util/getAuditLogData(referenceId='DT2502000025',processCode='101')
Authorization: Bearer {{token}}
Content-Type: application/json

### Test getAuditLogData endpoint with CWS process
GET {{host}}/util/getAuditLogData(referenceId='CR2502000017',processCode='201')
Authorization: Bearer {{token}}
Content-Type: application/json

### Test getAuditLogData endpoint with NED process
GET {{host}}/util/getAuditLogData(referenceId='CR2502000018',processCode='202')
Authorization: Bearer {{token}}
Content-Type: application/json

### Test getAuditLogData endpoint with OPWN process
GET {{host}}/util/getAuditLogData(referenceId='CR2502000019',processCode='203')
Authorization: Bearer {{token}}
Content-Type: application/json

### Test getAuditLogData endpoint with PTT process (should include eClaims items)
GET {{host}}/util/getAuditLogData(referenceId='DT2502000025',processCode='101')
Authorization: Bearer {{token}}
Content-Type: application/json

### Test getAuditLogData endpoint with CW process (should include eClaims items)
GET {{host}}/util/getAuditLogData(referenceId='DT2502000026',processCode='102')
Authorization: Bearer {{token}}
Content-Type: application/json

### Test releaseLockedRequests endpoint with specific draft ID
GET {{host}}/util/releaseLockedRequests(draftId='DT2502000025')
Authorization: Bearer {{token}}
Content-Type: application/json

### Test releaseLockedRequests endpoint without draft ID (unlocks all)
GET {{host}}/util/releaseLockedRequests()
Authorization: Bearer {{token}}
Content-Type: application/json

### Test requestLock endpoint for eClaims process (PTT)
### Note: NUSNET_ID will be extracted from XSUAA (request.user.id)
POST {{host}}/util/requestLock
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "DRAFT_ID": "DT2502000025",
  "PROCESS_CODE": "101",
  "REQUEST_STATUS": "LOCK",
  "REQUESTOR_GRP": "ESS"
}

### Test requestLock endpoint for CWS process
### Note: NUSNET_ID will be extracted from XSUAA (request.user.id)
POST {{host}}/util/requestLock
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "DRAFT_ID": "CWS2502000025",
  "PROCESS_CODE": "201",
  "REQUEST_STATUS": "LOCK",
  "REQUESTOR_GRP": "ESS"
}

### Test requestLock endpoint to unlock
### Note: NUSNET_ID will be extracted from XSUAA (request.user.id)
POST {{host}}/util/requestLock
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "DRAFT_ID": "DT2502000025",
  "PROCESS_CODE": "101",
  "REQUEST_STATUS": "UNLOCK",
  "REQUESTOR_GRP": "ESS"
}
