@xsuaaHostname = https://nus-ariba-dev-px55m7l5.authentication.eu10.hana.ondemand.com
@xsuaaClient = sb-utility!t169063
@xsuaaSecret = 8f6e922d-4d5d-4fe6-910f-000dce2b4638$tk1PCoekKMDcX4OIh88nJSgmdU2bERyXw_RLMtfY_vA=
@host = localhost:4004
@protocol = https
@unsecureProtocol = http

### Request-1 Get xsuaa token
#==================================================================#
# @name getXsuaaToken

POST {{xsuaaHostname}}/oauth/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{xsuaaClient}}:{{xsuaaSecret}}

client_id={{xsuaaClient}}
&client_secret={{xsuaaSecret}}
&grant_type=client_credentials

### Store access token 
@access_token = {{getXsuaaToken.response.body.$.access_token}}

### Request-1 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/catalog/eclaims_data
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-2 MASTER_CLAIM_TYPE
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='TASK_ACTION_CONFIG')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-2 CHRS_COMP_INFO
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='CHRS_COMP_INFO')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-3 ECLAIMS_DATA
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='ECLAIMS_DATA')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-3 ECLAIMS_ITEMS_DATA
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='ECLAIMS_ITEMS_DATA')
Content-Type: application/json
Authorization: Bearer {{access_token}}


### Request-3 REMARKS_DATA
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='REMARKS_DATA')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-3 ATTACHMENTS_DATA
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='ATTACHMENTS_DATA')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-3 AUDIT_LOG_DATA
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='AUDIT_LOG_DATA')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-3 PROCESS_DETAILS
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='PROCESS_DETAILS')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-3 TASK_DETAILS
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='TASK_DETAILS')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-3 DASHBOARD_CONFIG
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='DASHBOARD_CONFIG')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-3 CHRS_APPROVER_MATRIX
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='CHRS_APPROVER_MATRIX')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-3 APP_CONFIGS
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='APP_CONFIGS')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-3 CWS_APP_CONFIGS
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='CWS_APP_CONFIGS')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-4 Get User Detail
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/util/getUserDetails()
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-5 CHRS_ELIG_CRITERIA
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='CHRS_ELIG_CRITERIA')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-5 RATE_TYPE_MASTER_DATA
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='RATE_TYPE_MASTER_DATA')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-3 CWS DATA
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='CWS_DATA')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-3 CWS_PAYMENT_DATA
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='CWS_PAYMENT_DATA')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-3 OPWN_PAYMENT_IMG_DATA
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='OPWN_PAYMENT_IMG_DATA')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-3 OPWN_OTP_CONSOLIDATED_DATA
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='OPWN_OTP_CONSOLIDATED_DATA')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-3 CWS_ASSISTANCE_DATA
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='CWS_ASSISTANCE_DATA')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-3 CWS_WBS_DATA
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='CWS_WBS_DATA')
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Request-3 CWS_YEAR_SPLIT_DATA
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/rest/migration/loadTableData(Tablename='CWS_YEAR_SPLIT_DATA')
Content-Type: application/json
Authorization: Bearer {{access_token}}
