@xsuaaHostname = https://nus-ariba-dev-px55m7l5.authentication.eu10.hana.ondemand.com
@xsuaaClient = sb-utility!t169063
@xsuaaSecret = 606f8bda-ed4a-458d-ba53-927554a3c61c$Fq-f7jr_uYV2ONwMzuVZfaDLRDn7sRXDmSJn68Tzizg=
@host = localhost:4004
@protocol = https
@unsecureProtocol = http

### Request-1 Get xsuaa token
#==================================================================#
# @name getXsuaaToken

POST {{xsuaaHostname}}/oauth/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{xsuaaClient}}:{{xsuaaSecret}}

client_id={{xsuaaClient}}
&client_secret={{xsuaaSecret}}
&grant_type=client_credentials

### Store access token 
@access_token = {{getXsuaaToken.response.body.$.access_token}}

### Request-1 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/eclaims/eclaims/v_base_eclaim_request_view
Content-Type: application/json
Authorization: Bearer {{access_token}}


### Request-2 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/util/getUserDetails(userId='PTT_CA9')
Content-Type: application/json
Authorization: Bearer {{access_token}}



### Request-1 Get eclaims header data
#==================================================================#
GET {{unsecureProtocol}}://{{host}}/v2/catalog/v_approval_maxtrix?$filter=(STAFF_USER_GRP eq 'VERIFIER' and APM_VALID_FROM le '2024-09-04T06:54:58.069')
Content-Type: application/json
Authorization: Bearer {{access_token}}
