// entityFields.js

// Mapping from table/entity names (without namespace/context) to their field lists
const entityFields = {
    // ECLAIMS context
    HEADER_DATA: [
      'DRAFT_ID', 'REQUEST_ID', 'CLAIM_TYPE', 'STAFF_ID', 'STAFF_NUSNET_ID', 'CONCURRENT_STAFF_ID',
      'ULU', 'FDLU', 'EMPLOYEE_GRP', 'DATE_JOINED', 'EMP_RATE_TYPE', 'CLAIM_YEAR', 'CLAIM_MONTH',
      'REQUEST_STATUS', 'SUBMITTED_ON', 'SUBMITTED_BY', 'SUBMITTED_BY_NID', 'REQUESTOR_GRP',
      'CREATED_ON', 'ULU_T', 'FULL_NM', 'CLAIM_REQUEST_TYPE', 'MODIFIED_BY', 'MODIFIED_BY_NID',
      'MODIFIED_ON', 'WORKING_HOURS', 'STF_CLAIM_TYPE_CAT', 'APPOINTMENT_TRACK'
    ],
    ITEMS_DATA: [
      'ITEM_ID', 'DRAFT_ID', 'CLAIM_START_DATE', 'CLAIM_END_DATE', 'CLAIM_DAY_TYPE', 'IS_PH',
      'START_TIME', 'END_TIME', 'HOURS_COMPUTED', 'HOURS', 'CLAIM_MONTH', 'CLAIM_WEEK_NO', 'CLAIM_YEAR',
      'WBS', 'WBS_DESC', 'RATE_TYPE', 'RATE_TYPE_AMOUNT', 'IS_DISCREPENCY', 'DISC_RATETYPE_AMOUNT',
      'TOTAL_AMOUNT', 'IS_MULTIPLE', 'IS_MARK_DELETION', 'REMARKS', 'UPDATED_BY', 'UPDATED_ON',
      'CLAIM_DAY', 'RATE_UNIT', 'HOURS_UNIT', 'IS_DELETED', 'WAGE_CODE', 'OBJECT_ID', 'OBJECT_TYPE'
    ],
    TAX_BFT_CLAIMS_GRP: [
      'BEN_TYPE', 'START_DATE', 'END_DATE', 'TITLE', 'BEN_GROUP'
    ],
  
    // CWNED context
    CWNED_HEADER_DATA: [
      'REQ_UNIQUE_ID', 'REQUEST_ID', 'PROCESS_CODE', 'TYPE', 'REQUEST_TYPE', 'START_DATE', 'END_DATE',
      'START_DATE_CAL', 'END_DATE_CAL', 'FACULTY_C', 'DEPT_C', 'DURATION_DAYS', 'DURATION_HOURS',
      'SUB_TYPE', 'CLIENT_NAME', 'LOCATION', 'WORK_DETAILS', 'WORK_HOURS', 'TIME_OFF_REQD',
      'PROPERTY_USAGE', 'PROPERTY_DETAILS', 'STAFF_ID', 'CONCURRENT_STAFF_ID', 'OFFLINE_APPROVAL',
      'IS_REQUEST_CLOSED', 'REQUEST_STATUS', 'REQUESTOR_GRP', 'SUBMITTED_BY', 'SUBMITTED_ON',
      'MODIFIED_BY', 'MODIFIED_ON', 'STAFF_NUSNET_ID', 'ULU', 'FDLU', 'SUBMITTED_ON_TS',
      'SUBMITTED_BY_NID', 'SUBMISSION_TYPE', 'TO_DISPLAY', 'PROGRAM_NAME', 'AMOUNT', 'AGREED_AMOUNT',
      'CURRENCY', 'AGREED_CURRENCY', 'MIGRATED', 'MASS_REF_VAL', 'MASS_REF_UPLOAD_ID', 'SOURCE',
      'IS_OFN_EXECUTED', 'OFN_EXTRACT_DATE', 'IS_WAIVED', 'IS_ZIP_PROCESSED'
    ],
    YEAR_SPLIT_DATA: [
      'SPLIT_ID', 'REFERENCE_ID', 'YEAR', 'DURATION', 'TOTAL_UTILIZATION_YR',
      'CREATED_BY', 'CREATED_ON', 'MODIFIED_BY', 'MODIFIED_ON', 'IS_DELETED'
    ],
    ASSISTANCE_DATA: [
      'ASSISTANCE_ID', 'REFERENCE_ID', 'STAFF_ID', 'STAFF_NAME', 'STAFF_ULU', 'STAFF_FDLU',
      'CREATED_BY', 'CREATED_ON', 'MODIFIED_BY', 'MODIFIED_ON', 'IS_DELETED'
    ],
    WBS_DATA: [
      'ID', 'REFERENCE_ID', 'WBS', 'VALUE', 'UNIT', 'CREATED_BY', 'CREATED_ON',
      'MODIFIED_BY', 'MODIFIED_ON', 'IS_DELETED', 'WBS_CODE'
    ],
    PAYMENT_DATA: [
      'PAYMENT_ID', 'REFERENCE_ID', 'REQUEST_TYPE', 'YEAR', 'PAYMENT_DATE', 'PAYMENT_DATE_CAL',
      'PAYMENT_REF_NO', 'REMUNERATION_TYPE', 'STOCK_QNTY', 'STOCK_OPTION_QNTY', 'UNIT_TYPE',
      'SHARES', 'CURRENCY', 'AMOUNT', 'DESCRIPTION', 'LEVY_AMOUNT', 'IS_WAIVED', 'BIZ_EXP_CRNCY',
      'BIZ_EXP_AMT', 'PAYMENT_REQ_STATUS', 'CREATED_BY', 'CREATED_ON', 'MODIFIED_BY', 'MODIFIED_ON',
      'PAYMENT_TYPE', 'IS_DELETED', 'MONTH', 'WBS', 'OBJ_KEY', 'INVOICE_NO', 'CLR_DOC_NO'
    ],
    OPWN_PAYMENT_IMG_DATA: [
      'PAYMENT_ID', 'REFERENCE_ID', 'REQ_REFERENCE_ID', 'STAFF_ID', 'MONTH', 'YEAR', 'WBS',
      'ALLOTMENT_VAL', 'PAYMENT_TYPE_R', 'PAYMENT_TYPE_C', 'AMOUNT', 'CURRENCY', 'PAYMENT_DATE',
      'PAYMENT_DATE_CAL', 'PAYMENT_REQ_STATUS', 'ADMIN_LAPSE', 'MODIFIED_BY', 'MODIFIED_ON',
      'SF_SEQUENCE', 'MESSAGE_LOG'
    ],
    OPWN_OTP_CONSOLIDATED_DATA: [
      'SF_SEQUENCE', 'STAFF_ID', 'CURRENCY', 'WBS', 'REQ_REFERENCE_ID', 'REFERENCE_ID',
      'PAYMENT_TYPE_C', 'PAYMENT_DATE', 'PAYMENT_DATE_CAL', 'VALUE', 'POSTING_STATUS', 'MODIFIED_BY',
      'MODIFIED_ON', 'MESSAGE_LOG', 'MONTH', 'YEAR'
    ],
    OPWN_OTP_CONSOLIDATED_ERR_DATA: [
      'SF_SEQUENCE', 'STAFF_ID', 'CURRENCY', 'WBS', 'REQ_REFERENCE_ID', 'REFERENCE_ID',
      'PAYMENT_TYPE_C', 'PAYMENT_DATE', 'PAYMENT_DATE_CAL', 'VALUE', 'POSTING_STATUS', 'MODIFIED_BY',
      'MODIFIED_ON', 'MESSAGE_LOG', 'MONTH', 'YEAR'
    ],
    REPORT_EXTRACT_DATA: [
      'REP_EXTRACT_ID', 'REQ_UNIQUE_ID', 'PAYMENT_ID', 'REQUEST_ID', 'PROCESS_INST_ID', 'PROCESS_NAME',
      'PROCESS_TITLE', 'PROCESS_CODE', 'TYPE', 'REQUEST_TYPE', 'START_DATE', 'END_DATE', 'START_DATE_CAL',
      'END_DATE_CAL', 'FACULTY_C', 'FACULTY_T', 'DEPT_C', 'DEPT_T', 'DURATION_DAYS', 'DURATION_HOURS',
      'SUB_TYPE', 'SUB_TYPE_T', 'CLIENT_NAME', 'LOCATION', 'LOCATION_T', 'WORK_DETAILS', 'WORK_HOURS',
      'WORK_HOURS_T', 'TIME_OFF_REQD', 'PROPERTY_USAGE', 'PROPERTY_USAGE_T', 'PROPERTY_USAGE_R',
      'PROPERTY_DETAILS', 'STAFF_ID', 'FULL_NM', 'CONCURRENT_STAFF_ID', 'RM_STF_N', 'RMM_STF_N',
      'HRP_STF_N', 'OFFLINE_APPROVAL', 'IS_REQUEST_CLOSED', 'REQUEST_STATUS', 'REQUEST_STATUS_ALIAS',
      'REQUEST_STATUS_COLOR_CODE', 'REQUESTOR_GRP', 'SUBMITTED_ON', 'MODIFIED_BY', 'MODIFIED_ON',
      'STAFF_NUSNET_ID', 'ULU', 'ULU_C', 'ULU_T', 'ENG_ULU_T', 'FDLU', 'FDLU_C', 'FDLU_T', 'ENG_FDLU_T',
      'SUBMITTED_ON_TS', 'SUBMITTED_BY', 'SUBMITTED_BY_NID', 'SUBMITTED_BY_FULLNAME', 'SUBMISSION_TYPE',
      'SUBMISSION_TYPE_T', 'SUBMISSION_TYPE_REF_T', 'TO_DISPLAY', 'PROGRAM_NAME', 'AMOUNT_PAYABLE',
      'TOTAL_AMOUNT', 'BALANCE_AMOUNT', 'PAID_AMOUNT', 'AGREED_AMOUNT', 'CURRENCY', 'AGREED_CURRENCY',
      'MIGRATED', 'MASS_REF_VAL', 'MASS_REF_UPLOAD_ID', 'SOURCE', 'IS_WAIVED', 'IS_ZIP_PROCESSED',
      'YEAR', 'PAYMENT_DATE', 'PAYMENT_DATE_CAL', 'PAYMENT_REF_NO', 'REMUNERATION_TYPE',
      'REMUNERATION_TYPE_T', 'STOCK_QNTY', 'STOCK_OPTION_QNTY', 'UNIT_TYPE', 'UNIT_TYPE_T', 'SHARES',
      'PAYMENT_CURRENCY', 'AMOUNT', 'DESCRIPTION', 'LEVY_AMOUNT', 'IS_PYMT_WAIVED', 'BIZ_EXP_CRNCY',
      'BIZ_EXP_AMT', 'PAYMENT_REQ_STATUS', 'PAYMENT_REQ_STATUS_STATE', 'PAYMENT_REQ_STATUS_ALIAS',
      'CREATED_BY', 'CREATED_ON', 'PAYMENT_TYPE', 'PAYMENT_TYPE_C', 'PAYMENT_TYPE_ALIAS', 'IS_DELETED',
      'MONTH', 'AMENDED_WBS', 'AMENDED_ALLOT_VAL', 'OBJ_KEY', 'INVOICE_NO', 'CLR_DOC_NO',
      'OFFLINE_ADJUSTMENT', 'FS_POSTED_ON', 'APPROVED_BY', 'APPROVED_ON', 'APPROVED_BY_FULL_NAME',
      'LAST_SYNCED_ON'
    ],
  
    // UTILITY context
    SEQ_GEN: ['PATTERN', 'RUNNINGNO'],
    BTP_CREDENTIALS: [
      'CID', 'ACC_TYPE', 'END_POINT', 'ACC_NAME', 'ACC_SECRET', 'CUSTOM_ATTR_1', 'CUSTOM_ATTR_2',
      'CUSTOM_ATTR_3', 'CUSTOM_ATTR_4'
    ],
    EMAIL_TEMPLATES: [
      'TEMPLATE_NAME', 'MAIL_SUBJECT', 'MAIL_BODY', 'CONTENT_TYPE', 'UPDATED_BY', 'UPDATED_BY_NID',
      'UPDATED_ON', 'PROCESS_CODE', 'TEMPLATE_DESC'
    ],
    EMAIL_CONFIGS: [
      'ECONFIG_ID', 'TEMPLATE_NAME', 'EMAIL_DESC', 'PROCESS_CODE', 'TASK_NAME', 'ACTION_CODE',
      'REQUEST_STATUS', 'EMAIL_TYPE', 'RECIPIENT_TYPE', 'RECIPIENT_LIST', 'EMAIL_STATUS',
      'EMAIL_API_NAME', 'UPDATED_BY', 'UPDATED_BY_NID', 'UPDATED_ON', 'RECIPIENT_CC'
    ],
    EMAIL_PLACEHOLDER_CONFIG: [
      'EPH_ID', 'TEMPLATE_NAME', 'TASK_NAME', 'PH_TYPE', 'FIELD_TYPE', 'FIELD_KEY', 'FIELD_VALUE',
      'FIELD_VALUE_PROP', 'DISPLAY_SEQ', 'UPDATED_BY', 'UPDATED_BY_NID', 'UPDATED_ON'
    ],
    AUDIT_LOG_DATA: [
      'AUDIT_ID', 'REFERENCE_ID', 'CHANGED_ON', 'CHANGED_BY', 'SECTION', 'IDENTITY', 'SUB_SECTION',
      'FIELD_LABEL', 'OLD_VALUE', 'OLD_VALUE_DESC', 'NEW_VALUE', 'NEW_VALUE_DESC', 'FIELD_TYPE',
      'ACTION_TYPE', 'CUSTOM_ATTR_1', 'CUSTOM_ATTR_2'
    ],
    ATTACHMENTS_DATA: [
      'ATTCHMNT_ID', 'REFERENCE_ID', 'HIERARCHY', 'SOURCE_TYPE', 'OPNTXT_ID', 'ATTACHMENT_TYPE',
      'ATTACHMENT_NAME', 'ATTACHMENT_URL', 'MEDIA_TYPE', 'EXPIRY_DATE', 'UPLOADED_BY', 'UPDATED_BY_NID',
      'UPLOADED_ON', 'IS_DELETED', 'MODIFIED_BY', 'MODIFIED_BY_NID', 'MODIFIED_ON', 'IS_ZIP_PROCESSED'
    ],
    NOTIFICATION_LOG_DATA: [
      'NOTIF_ID', 'REFERENCE_ID', 'NOTIF_TEMPLATE_ID', 'NOTIF_TYPE', 'RECIPIENT_LIST', 'RECIPIENT_TYPE',
      'NOTIF_STATUS', 'NOTIF_STATUS_MSG', 'SENT_BY', 'SENT_BY_NUSNET_ID', 'SENT_ON', 'PROCESS_CODE',
      'TASK_NAME'
    ],
    STATUS_CONFIG: [
      'STATUS_CODE', 'STATUS_TYPE', 'STATUS_ALIAS', 'STATUS_COLOR_CODE', 'STATUS_DESC', 'STATUS_STATE',
      'SHOW_INBOX'
    ],
    REMARKS_DATA: [
      'ID', 'REFERENCE_ID', 'REMARKS', 'STAFF_ID', 'STAFF_NAME', 'STAFF_USER_TYPE', 'REMARKS_UPDATE_ON',
      'REMARKS_TYPE', 'NUSNET_ID', 'IS_EDITABLE'
    ],
    PROCESS_DETAILS: [
      'PROCESS_INST_ID', 'REFERENCE_ID', 'PROCESS_CODE', 'PROCESS_STATUS', 'PROCESS_START_DATE',
      'PROCESSED_BY', 'PROCESSED_BY_NID', 'PROCESS_EXPECTED_DOC', 'PROCESS_ACTUAL_DOC'
    ],
    TASK_DETAILS: [
      'TASK_INST_ID', 'PROCESS_INST_ID', 'TASK_NAME', 'TASK_STATUS', 'TASK_CREATED_ON', 'TASK_CREATED_BY',
      'TASK_ASSGN_TO', 'TASK_ASSGN_GRP', 'TASK_COMPLETED_BY', 'TASK_COMPLETED_BY_NID', 'TASK_EXPECTED_DOC',
      'TASK_ACTUAL_DOC', 'TASK_SEQUENCE', 'ACTION_CODE', 'TO_BE_TASK_SEQUENCE', 'TASK_ASSGN_TO_STF_NUMBER',
      'TASK_CREATED_BY_NID'
    ],
    PROCESS_CONFIG: [
      'PROCESS_CODE', 'PROCESS_NAME', 'PROCESS_TITLE', 'PROCESS_SLA_DAYS', 'REFERENCE_KEY'
    ],
    TASKS_CONFIG: [
      'TCFG_ID', 'PROCESS_CODE', 'REQUESTOR_GRP', 'TASK_NAME', 'TASK_ALIAS', 'TASK_SEQUENCE',
      'TASK_SLA_DAYS', 'IS_MANDATORY', 'SOURCE_ACCESS', 'TASK_GRP', 'TASK_REQUEST_STATUS'
    ],
    TASK_ACTION_CONFIG: [
      'TACTION_ID', 'REQUESTOR_GRP', 'TASK_NAME', 'ACTION_CODE', 'ACTION_NAME', 'CURRENT_TASK_SEQUENCE',
      'TO_BE_TASK_SEQUENCE', 'TO_BE_PROCESS_STATUS', 'TO_BE_REQUEST_STATUS', 'BUTTON_TYPE', 'DISPLAY_ICON',
      'SEQUENCE_ORDER', 'DISPLAY_REQD', 'PROCESS_CODE', 'ACTION_ALIAS'
    ],
    CLAIM_REQUEST_DURATION_CONFIG: [
      'CONFIG_ID', 'CLAIM_TYPE_C', 'CLAIM_TYPE_T', 'REQUESTOR_GRP', 'REQUEST_RANGE_MONTHS', 'CREATED_BY',
      'CREATED_ON', 'UPDATED_BY', 'UPDATED_ON'
    ],
    PROCESS_PARTICIPANTS: [
      'PPNT_ID', 'REFERENCE_ID', 'USER_DESIGNATION', 'STAFF_ID', 'NUSNET_ID', 'UPDATED_BY',
      'UPDATED_BY_NID', 'UPDATED_ON', 'STAFF_FULL_NAME', 'IS_DELETED'
    ],
    TASK_DELEGATION_DETAILS: [
      'ID', 'TASK_NAME', 'DELEGATED_TO', 'DELEGATED_TO_NID', 'PROCESS_TYPE', 'VALID_FROM', 'VALID_TO',
      'CREATED_BY', 'CREATED_ON', 'CREATED_BY_NID', 'ASSIGNED_TO', 'DELEGATED_FOR', 'DELEGATED_FOR_NID',
      'MODIFIED_BY', 'MODIFIED_ON', 'MODIFIED_BY_NID', 'IS_DELETE', 'PROCESS_CODE', 'DELIMIT_IND'
    ],
    APP_CONFIGS: [
      'ACFG_ID', 'PROCESS_CODE', 'CONFIG_DESC', 'CONFIG_KEY', 'CONFIG_VALUE', 'IS_MAINT_BY_USER',
      'UPDATED_BY', 'UPDATED_BY_NID', 'UPDATED_ON'
    ],
    CWS_APP_CONFIGS: [
      'CWS_ACFG_ID', 'PROCESS_CODE', 'REFERENCE_KEY', 'CONFIG_KEY', 'CONFIG_VALUE', 'REFERENCE_VALUE',
      'CONFIG_DESC', 'CFG_TYPE', 'IS_ACTIVE', 'CREATED_BY', 'CREATED_ON', 'MODIFIED_BY', 'MODIFIED_ON'
    ],
    CWS_ULU_EMAIL_CONFIG: [
      'CWS_ACFG_ID', 'ULU', 'GRP_EMAIL', 'IS_ACTIVE', 'CREATED_BY', 'CREATED_ON'
    ],
    CHRS_ROLE_MASTER: [
      'ROLE_ID', 'PROCESS_CODE', 'ROLE_CODE', 'ROLE_CODE_LBL', 'IS_ACTIVE', 'MODIFIED_BY', 'MODIFIED_ON'
    ],
    CHRS_APPROVER_MATRIX: [
      'AUTH_ID', 'PROCESS_CODE', 'ULU', 'FDLU', 'STAFF_USER_GRP', 'STAFF_NUSNET_ID', 'STAFF_ID',
      'VALID_FROM', 'VALID_TO', 'IS_EXCLUDED', 'UPDATED_BY', 'UPDATED_BY_NID', 'UPDATED_ON',
      'IS_DELETED', 'APM_VALID_FROM', 'APM_VALID_TO', 'PROCESS_TYPE'
    ],
    REQUEST_LOCK_DETAILS: [
      'LOCK_INST_ID', 'REFERENCE_ID', 'PROCESS_CODE', 'ULU', 'FDLU', 'IS_LOCKED', 'LOCKED_BY_USER_NID',
      'VALID_FROM', 'VALID_TO', 'STAFF_USER_GRP', 'REQUEST_STATUS', 'LOCKED_ON'
    ],
    DASHBOARD_CONFIG: [
      'DS_ACFG_ID', 'ACCESS_ROLE', 'REFERENCE_KEY', 'SEQUENCE', 'CONFIG_KEY', 'CONFIG_VALUE', 'FIELD_TYPE',
      'IS_ACTIVE', 'CREATED_BY', 'MODIFIED_BY', 'CONFIG_DATA', 'PROCESS_CODE'
    ],
    FEEDBACK_DETAILS: [
      'SEQ_NO', 'STF_NO', 'STF_NAME', 'ISSUE_DATE', 'APP_NAME', 'REMARKS', 'CREATED_BY', 'CREATED_ON'
    ],
    NUS_CHRS_HOLIDAYS: [
      'SEQ_NO', 'DATE', 'DAY', 'MONTH', 'YEAR', 'HOLIDAY_TYPE', 'HOLIDAY_NAME', 'HOLIDAY_DESC', 'PTT', 'OT', 'CW'
    ],
    DATE_TO_WEEK: [
      'WEEK', 'START_DATE', 'END_DATE'
    ]
}

function getEntityFields(entityName) {
    return entityFields[entityName] || [];
  }
  
module.exports = { getEntityFields, entityFields };
